---
apiVersion: v1
kind: Config
clusters:
- name: local
  cluster:
    certificate-authority: {{ kube_cert_dir }}/ca.pem
users:
- name: kubelet
  user:
    client-certificate: {{ kube_cert_dir }}/worker.pem
    client-key: {{ kube_cert_dir }}/worker-key.pem
contexts:
- context:
    cluster: local
    user: kubelet
  name: kubelet-context
current-context: kubelet-context
